model:
  batch_norm: False
  crossing_layers: 3
  dnn_hidden_units: [2000, 2000, 2000]
  dnn_activations: relu
  embedding_dim: 16
  embedding_dropout: 0
  embedding_regularizer: 1.0e-08
  net_dropout: 0
  net_regularizer: 0


optim:
  lr: 0.001